const getters = {
  rootUrl: state => state.app.rootUrl,
  apiUrl: state => state.app.apiUrl,
  qiniuTicket: state => state.app.qiniuTicket,
  authType: state => state.app.authType,
  sortList: state => state.app.sortList,
  operationList: state => state.app.operationList,
  articleStatusList: state => state.app.articleStatusList,

  id: state => state.user.id,
  name: state => state.user.name,
  avatar: state => state.user.avatar,
  avatarUrl: state => state.user.avatarUrl,
  role: state => state.user.role,
  rolelist: state => state.user.rolelist,
  status: state => state.user.status,
  phone: state => state.user.phone,
  hospital: state => state.user.hospital,
  certificate: state => state.user.certificate,
  gender: state => state.user.gender,
  genderlist: state => state.user.genderlist,
  department: state => state.user.department,
  agency: state => state.user.agency,
  friend: state => state.user.friend,
  title: state => state.user.title,
  treatment_info: state => state.user.treatment_info,
  description: state => state.user.description,
};
export default getters;
